dakara_player_vlc/tests.py, dakara_player_vlc/tests_dakara_manager.py, dakara_player_vlc/tests_dakara_server.py, dakara_player_vlc/tests_font_loader.py, dakara_player_vlc/tests_text_generator.py, dakara_player_vlc/tests_vlc_player.py
Logging of the modules of the project is now enabled if the verbosity of the test is set.
=> Allow to show logging in tests on verbose mode

CHANGELOG.md, dakara_player_vlc/tests_text_generator.py, dakara_player_vlc/text_generator.py, share/transition.ass
This PR follows the changes induced in [this PR on the server](https://github.com/DakaraProject/dakara-server/pull/62).
Long name of the link type is now hard-coded. A new filter allows to get the name of a link type. Previous filter (for icons) has been moved to its own function. Documentation and tests have been enhanced.
=> Make work link type name hard coded

.gitignore, dakara_player_vlc/resources/tests/config.yaml, dakara_player_vlc/safe_workers.py, dakara_player_vlc/tests/tests_dakara_player_vlc.py
The PR #25 did not add tests to the Dakara player VLC module (the main module), since it was a simple container for the instances of the other classes of the package. This miss made the issue #35 occur, as it reveals that some critical tasks of the module are not tested.
This PR aims to fix the issue and to add tests to prevent similar problems in the future.
=> Add tests to the main module

CHANGELOG.md, src/dakara_player_vlc/font_loader.py, tests/test_font_loader.py
Two bugs have been solved on the font loader for Linux:
* Automatically remove font dead symlinks that made the program fail. A dedicated piece of code handle this now;
* Properly unload fonts. Before, unloading was modifying the list of installed fonts, which altered the for loop it was called from. Now the for loop operates from a copy of the list.
=> Fix font loading/unloading problems

setup.cfg, src/dakara_player_vlc/state_manager.py, src/dakara_player_vlc/vlc_player.py, tests/unit/test_state_manager.py
This is a quick and dirty fix for the exception that rises at the end of playlist. Since the states system introduced by #68 will be removed, we won't assess this problem deeply.
=> Quick fix for the crash at end of playlist

CHANGELOG.md, src/dakara_player/media_player/vlc.py, src/dakara_player/resources/player.yaml, src/dakara_player/window.py, tests/integration/test_media_player_vlc.py, tests/unit/test_media_player_vlc.py, tests/unit/test_window.py
Fixes #6, fixes #15.
When VLC manages its own window, it will create a new one for every media. On Linux, the window stays more or less open, so this is not that much noticeable, but on Windows, the window manager animation makes it impossible to miss, as reported in #15. More over, this approach suffers from bugs: some videos can break fullscreen mode (#6) or, on dual screen, the window can be opened on a different monitor (the one where the cursor is).
This MR aims to create a single, permanent window with Tkinter and to assign VLC to render in it using [`set_xwindow`](https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.MediaPlayer-class.html#set_xwindow) on Linux, and [`set_hwnd`](https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.MediaPlayer-class.html#set_hwnd) on Windows.
=> Make VLC run in a permanet window

.appveyor.yml, README.md
VLC version 3.0.13 and 3.0.14 crashes with the Python-VLC wrapper, even for simple cases. Before having a permanent solution, this PR restrict installation of VLC to different versions.
See also https://github.com/oaubert/python-vlc/issues/178.
=> Fix VLC crash temporarily

src/dakara_player/media_player/vlc.py, tests/unit/test_media_player_vlc.py
This PR blacklists known incompatible versions of VLC with the player.
=> Blacklist VLC versions 3.0.13 and 3.0.14

src/dakara_player/dakara_manager.py, src/dakara_player/media_player/base.py, src/dakara_player/media_player/mpv.py, src/dakara_player/media_player/vlc.py, tests/integration/test_media_player_mpv.py, tests/integration/test_media_player_vlc.py
Fix #90 for Mpv.
Check initial state of the media players when they are just starting.
=> Skip any song before playing the idle screen

.appveyor.yml, CHANGELOG.md, README.md, src/dakara_player/media_player/vlc.py, tests/unit/test_media_player_vlc.py
Blacklist the concerned versions.
~Redo tests when VLC 3.0.17 is available on [Chocolatey](https://community.chocolatey.org/packages/vlc).~ Done.
=> Manage VLC crashes for versions 3.0.13 to 3.0.16

src/dakara_player/media_player/mpv.py
A patch was proposed and integrated in `python_mpv_jsonipc`, but no new release was done. The library is monkey patched to obtain the same result.
=> Silent mpv socket close failures on Windows

CHANGELOG.md, README.md, setup.cfg, src/dakara_player/font.py, src/dakara_player/media_player/base.py, src/dakara_player/media_player/vlc.py, src/dakara_player/user_resources.py, tests/unit/test_font.py, tests/unit/test_media_player_vlc.py, tests/unit/test_user_resources.py
This PR allows to use a new library in Dakara base for managing user directory across different operating systems.
Part of the work was done in c4b3bedd1055e3b595eb43ad1578090a5c1e7d2a. Parts of #107 were ported to this PR.
=> New management of directories

.github/workflows/ci.yml, CHANGELOG.md, pyproject.toml, src/dakara_player/background.py, src/dakara_player/font.py, src/dakara_player/text.py, src/dakara_player/user_resources.py
This MR aims to drop the latest unsupported Python version (3.7) and support the latest version (3.12).
This MR may need the latest `dakara-base` version, to support the in-house implementation of `strtobool`.
=> Drop Python 3.7 support and add Python 3.12 support

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg, tests/unit/test_media_player_mpv.py
ruff runs pretty fast, which is nice when used as a pre-commit hook.
It also implements more checks that can be selected as needed, in this
PR I add the bugbear (B) checks which were not present in the
previous configuration and fix the issue it reports.
=> setup ruff as a flake8 replacement

.github/workflows/ci.yml
Wait for all tests to complete before uploading code coverage. Previously the unit tests would upload their results in advance and the codecov bot would report coverage issues in new PRs.
As it is, the workflow will not upload code coverage reports if any of the unit or integration tests fail. Which I think is fine.
=> ci: upload code coverage in a separate step

src/dakara_player/media_player/vlc.py, tests/unit/test_media_player_vlc.py
This would make the tests fail on a system without VLC installed. Detecting it in is_available skips the tests.
For reference this is the error I get:
```
Traceback (most recent call last):
File "/home/odrling/git/misc/dakara-player/src/dakara_player/media_player/vlc.py", line 94, in is_available
return vlc is not None and vlc.Instance() is not None
^^^^^^^^^^^^^^
File "/home/odrling/git/misc/dakara-player/.direnv/python-3.12/lib/python3.12/site-packages/vlc.py", line 1838, in __new__
return libvlc_new(len(args), args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/odrling/git/misc/dakara-player/.direnv/python-3.12/lib/python3.12/site-packages/vlc.py", line 5014, in libvlc_new
_Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
File …
```
=> vlc: catch errors when instanciating vlc in is_available

.github/workflows/ci.yml
mpv 0.38.0 is available in the Chocolatey repository and should work fine for our needs.
Tests won't pass without #123
=> ci: remove lock on windows' mpv version

.github/workflows/ci.yml
~~The ubuntu-24.04 image is in beta (so it is not ubuntu-latest yet)~~ Ubuntu 24.04 is now available through `ubuntu-latest`:
- https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
- https://github.com/actions/runner-images/issues/10636
=> ci: use ubuntu 24.04 image

pyproject.toml, src/dakara_player/__main__.py, src/dakara_player/audio.py, src/dakara_player/background.py, src/dakara_player/font.py, src/dakara_player/media_player/base.py, src/dakara_player/media_player/mpv.py, src/dakara_player/media_player/vlc.py, src/dakara_player/mrl.py, src/dakara_player/player.py, src/dakara_player/text.py, src/dakara_player/user_resources.py, tests/integration/base.py, tests/integration/test_media_player_mpv.py, tests/integration/test_media_player_vlc.py, tests/unit/test_audio.py, tests/unit/test_background.py, tests/unit/test_font.py, tests/unit/test_media_player_mpv.py, tests/unit/test_media_player_vlc.py, tests/unit/test_mrl.py, tests/unit/test_player.py, tests/unit/test_text.py, tests/unit/test_user_resources.py, tests/utils.py
Remove `path` in the spirit of DakaraProject/dakara-base#51.
=> Remove `path` in favor of `pathlib`

src/dakara_player/media_player/mpv.py, tests/integration/test_media_player_mpv.py
Fixes #138.
But I don't like that a variable may contain `None`, `"self"` and a `pathlibi.Path` instance at the same time.
=> Fix `"None"` passed as audio file by default

src/dakara_player/media_player/mpv.py, src/dakara_player/media_player/vlc.py, tests/integration/test_media_player_mpv.py, tests/unit/test_media_player_vlc.py
- For mpv: `SongMedia.track_id_audio` stores the instrumental track ID and `USE_PATH_AUDIO` if an instrumental file should be used;
- For VLC: Do some renaming.
=> Improve management of instrumental tracks
